/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte.teachers;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

class AppTest {


    @BeforeAll
    static void initLerngruppen(){

    }

    @Test
    void testListLerngruppenSchueler() {

    }
}
