/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte.teachers;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void testAdd() {
        assertEquals(4, 2 + 2);
    }
}
