/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.maxkorte.teachers;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class SchuelerTest {
    static Schueler s;

    @Test
    @DisplayName("tests to create a schueler with null arguments")
    void testSchuler() {
        Assertions.assertThrows(IllegalArgumentException.class, () -> {
            new Schueler(null, null);
        });
    }

    @Test
    @BeforeAll
    static void initSchuler() {
        s = new Schueler("Max", "Mustermann;");
    }

    @Test
    void testAddGrade() {
        Assertions.assertThrows(QuartalException.class, () -> {
            s.addGrade(Integer.MIN_VALUE, 12);
            s.addGrade(Integer.MAX_VALUE, 0);
        });
        Assertions.assertThrows(PointsException.class, () -> {
            s.addGrade(3, Integer.MIN_VALUE);
            s.addGrade(3, Integer.MAX_VALUE);
        });
    }

    @Test
    void testGetH1H2Grade() throws Exception {
        Assertions.assertNull(s.getH1grade());
        Assertions.assertNull(s.getH2grade());

        addGrades();

        Assertions.assertEquals(11, s.getH1grade());
        Assertions.assertEquals(10.5, s.getH2grade());
    }

    private static void addGrades() throws Exception {
        s.addGrade(1, 10);
        s.addGrade(2, 12);
        s.addGrade(3, 8);
        s.addGrade(4, 13);
    }
}
