package com.maxkorte.teachers;

public enum Fach {
    DEUTSCH, MATHEMATIK, ENGLISCH, ERDKUNDE, GESCHICHTE, POLITIK, SOZIALWISSENSCHAFTEN, BIOLOGIE, CHEMIE, PHYSIK,
    INFORMATIK, FRANZOESISCH, SPANISCH, KUNST, MUSIK, RELIGIONSLEHRE, SPORT, ERZIEHUNGSWISSENSCHAFTEN
}
